### ISSUE TITLE
Inverted Camera Result

### ISSUE THREAD

**Issue by Tuzair** [blikoon/QRCodeScanner#25] opened 2019-01-30 10:50 UTC
The camera result is upside down.
![screenshot_20190130-154914 1](https://user-images.githubusercontent.com/47176818/51976555-c2a0cd00-24a6-11e9-94dd-6fbd06e66509.png)

**Comment by rutura** [comment] 2019-01-30 11:44
Duplicate of https://github.com/blikoon/QRCodeScanner/issues/8 .
Closing this.

**Closed as completed by rutura** 2019-01-30 11:44 UTC
