### ISSUE TITLE
cannot run on my phone

### ISSUE THREAD

**Issue by guttulasai** [blikoon/QRCodeScanner#17] opened 2018-08-02 16:23 UTC
hie..

i m sorry but i could not run this code on my phone..
it gives me a notification saying 'Could not open your camera'

**Comment by rutura** [comment] 2018-08-05 13:15
Duplicate of https://github.com/blikoon/QRCodeScanner/issues/11 .
Closing this.

**Closed as completed by rutura** 2018-08-05 13:15 UTC

**Comment by nehagote** [comment] 2018-08-13 06:54
I was facing the same issue adding Vibrate permission along with camera resolved my issue.
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.CAMERA" />
